import { recipe } from "@vanilla-extract/recipes";

export const flexStyle = recipe({
  base: {
    display: "flex",
  },
  variants: {
    full: {
      true: {
        flex: "1",
      },
    },
    direction: {
      row: { flexDirection: "row" },
      column: { flexDirection: "column" },
    },
    wrap: {
      wrap: { flexWrap: "wrap" },
      nowrap: { flexWrap: "nowrap" },
    },
    align: {
      start: { alignItems: "flex-start" },
      center: { alignItems: "center" },
      end: { alignItems: "flex-end" },
      stretch: { alignItems: "stretch" },
      baseline: { alignItems: "baseline" },
    },
    justify: {
      start: { justifyContent: "flex-start" },
      center: { justifyContent: "center" },
      end: { justifyContent: "flex-end" },
      between: { justifyContent: "space-between" },
      around: { justifyContent: "space-around" },
      evenly: { justifyContent: "space-evenly" },
    },
    gap: {
      0: { gap: "0" },
      1: { gap: "0.6rem" },
      2: { gap: "1.2rem" },
      3: { gap: "1.8rem" },
      4: { gap: "2.4rem" },
      5: { gap: "3rem" },
      6: { gap: "3.6rem" },
      7: { gap: "4.2rem" },
      8: { gap: "4.8rem" },
    },
    p: {
      0: { padding: "0" },
      1: { padding: "0.6rem" },
      2: { padding: "1.2rem" },
      3: { padding: "1.8rem" },
      4: { padding: "2.4rem" },
      5: { padding: "3rem" },
      6: { padding: "3.6rem" },
      7: { padding: "4.2rem" },
      8: { padding: "4.8rem" },
    },
    pl: {
      0: { paddingLeft: "0" },
      1: { paddingLeft: "0.6rem" },
      2: { paddingLeft: "1.2rem" },
      3: { paddingLeft: "1.8rem" },
      4: { paddingLeft: "2.4rem" },
      5: { paddingLeft: "3rem" },
      6: { paddingLeft: "3.6rem" },
      7: { paddingLeft: "4.2rem" },
      8: { paddingLeft: "4.8rem" },
    },
    pr: {
      0: { paddingRight: "0" },
      1: { paddingRight: "0.6rem" },
      2: { paddingRight: "1.2rem" },
      3: { paddingRight: "1.8rem" },
      4: { paddingRight: "2.4rem" },
      5: { paddingRight: "3rem" },
      6: { paddingRight: "3.6rem" },
      7: { paddingRight: "4.2rem" },
      8: { paddingRight: "4.8rem" },
    },
    pt: {
      0: { paddingTop: "0" },
      1: { paddingTop: "0.6rem" },
      2: { paddingTop: "1.2rem" },
      3: { paddingTop: "1.8rem" },
      4: { paddingTop: "2.4rem" },
      5: { paddingTop: "3rem" },
      6: { paddingTop: "3.6rem" },
      7: { paddingTop: "4.2rem" },
      8: { paddingTop: "4.8rem" },
    },
    pb: {
      0: { paddingBottom: "0" },
      1: { paddingBottom: "0.6rem" },
      2: { paddingBottom: "1.2rem" },
      3: { paddingBottom: "1.8rem" },
      4: { paddingBottom: "2.4rem" },
      5: { paddingBottom: "3rem" },
      6: { paddingBottom: "3.6rem" },
      7: { paddingBottom: "4.2rem" },
      8: { paddingBottom: "4.8rem" },
    },
  },
  defaultVariants: {
    direction: "row",
    wrap: "nowrap",
    align: "stretch",
    justify: "start",
    gap: 0,
  },
});
