import Head from "next/head";
import type { InferGetServerSidePropsType, GetServerSideProps } from "next";
import { createPagesServerClient } from "@supabase/auth-helpers-nextjs";
import { Footer } from "~/app/footer";
import { Header } from "~/app/header";
import { ProductDetail } from "~/app/product-detail";
import { Container } from "~/uikit/container";
import { Box } from "~/uikit/box";
import { Flex } from "~/uikit/flex";
import { Card } from "~/uikit/card";
import { Text } from "~/uikit/text";
import { Image } from "~/uikit/image";
import { Button } from "~/uikit/button";
import { ChevronRight } from "lucide-react";
import { useIsMobile } from "~/hooks/useIsMobile";

type Product = {
  id: number;
  slug: string;
  name: string;
  description: string;
  image_url: string;
  profile: {
    name: string;
    picture: string;
  };
};

type HomePageProps = {
  product: Product | null;
};

export const getServerSideProps = (async (ctx) => {
  const supabase = createPagesServerClient(ctx);
  const slug = ctx.params?.slug as string;

  const getProduct = async (slug: string) => {
    const { data: product } = await supabase
      .from("product")
      .select<
        any,
        Product
      >("id, name, description, image_url, slug, profile(name,picture)")
      .eq("slug", slug)
      .eq("status", true)
      .single();
    return product;
  };

  const [product] = await Promise.all([getProduct(slug)]);

  if (!product) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      product,
    },
  };
}) satisfies GetServerSideProps<HomePageProps>;

export default function ProductPage(
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) {
  const product = props.product;
  const isMobile = useIsMobile();

  const purchaseLinks = (
    <Box width={!isMobile ? 120 : undefined}>
      <Card>
        <Text weight="bold">Link Pembelian</Text>
        <Flex direction="column" gap={4} mt={4}>
          <Button full>
            <Image
              src="/tokopedia.svg"
              width={100}
              height={22}
              alt="Tokopedia Link"
            />
            <ChevronRight />
          </Button>

          <Button full>
            <Image
              src="/shopee.svg"
              width={100}
              height={32}
              alt="Shopee Link"
            />
            <ChevronRight />
          </Button>
        </Flex>
      </Card>
    </Box>
  );

  const productComponent = (
    <ProductDetail
      onLike={() => {}}
      onShare={() => {}}
      item={{
        id: product.id,
        title: product.name,
        description: product.description,
        imageUrl: product.image_url,
        slug: product.slug,
        likes: 0,
        tags: [],
        author: product.profile
          ? {
              name: product.profile.name,
              avatar: product.profile.picture,
            }
          : undefined,
        additionalImageUrls: [],
      }}
    />
  );

  return (
    <>
      <Head>
        <title>Sportify | {props.product?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Flex
          mt={8}
          gap={4}
          pl={4}
          pr={4}
          direction={isMobile ? "column" : "row"}
          full
        >
          {productComponent}
          {purchaseLinks}
        </Flex>
      </Container>
      <Footer />
    </>
  );
}
