import Head from "next/head";
import { Header } from "~/uikit/header/header";
import { Layout } from "~/uikit/layout/layout";
import { Sidebar } from "~/app/components/sidebar";
import { Text } from "~/uikit/text";
import { Container } from "~/uikit/container/container";
import { Card } from "~/uikit/card";
import { ProductList } from "~/app/containers/product-list";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sportify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container>
          <Layout
            leftNode={
              <Sidebar
                items={[
                  {
                    id: 1,
                    name: "Running",
                    href: "/categories/running",
                  },
                  {
                    id: 2,
                    name: "Soccer",
                    href: "/categories/soccer",
                  },
                  {
                    id: 3,
                    name: "Basketball",
                    href: "/categories/basketball",
                  },
                ]}
              />
            }
          >
            <ProductList
              items={[
                {
                  id: 1,
                  author: {
                    name: "John Doe",
                    avatar: "https://placehold.co/96x96",
                  },
                  imageUrl:
                    "https://images.tokopedia.net/img/cache/900/VqbcmM/2024/8/8/a1190e71-7363-4e42-b3c3-5fda2149e809.jpg",
                  title: "MILLS Sepatu Revolt Raze",
                  description: "Description",
                  likes: 69,
                },
                {
                  id: 2,
                  author: {
                    name: "Jane Doe",
                    avatar: "https://placehold.co/96x96",
                  },
                  imageUrl:
                    "https://www.adidas.co.id/media/catalog/product/i/h/ih7759_5_footwear_photography_side20medial20center20view_grey.jpg",
                  title: "Runfalcon 5 Running Shoes",
                  description: "Description",
                  likes: 69,
                },
              ]}
            />
          </Layout>
        </Container>
      </main>
    </>
  );
}
